### ISSUE TITLE
Vote not showing

### ISSUE THREAD

**Issue by ParadoxLeon** [justinnobledev/cs2-mapchooser#24]
When typing !rtv in chat i get the message that the vote is starting but nothing ever shows up.
Just installed this plugin on a new server.

This is my maps.txt
> de_dust2
> cs_offfice
> de_inferno
> de_nuke
> ws:de_dust2_classic
> ws:Assault (cs_assault)
> ws:Assembly
> ws:Vandal
> ws:Season (CS2) (unofficial port)
> ws:Biome CS2
> ws:CS2 Assault
> ws:Tides CS2 Port (CS:S)
> ws:Dust
> ws:de_aztec classic
> ws:Foroglio
> ws:Thera
> ws:Mirage (Mirror)
> ws:de_inferno [CS1.6]

**Server Info**
 - OS: Windows Server 2022
 - CSS Version: build-213
 - Plugin Version: 1.3

**Comment by justinnobledev** [comment]
My only guess with this is its something weird on windows, since #23  is also having similar problems and they also use windows. I use linux for all my servers and testing. Could you check console after a vote happens and see if some sort of error occurs in console?

Also your maps.txt wont work for example `ws:Assault (cs_assault)` is not a valid map name, you need to put in the actual name of cs_assault or w/e the workshop map is you can find these by typing `ds_workshop_listmaps` in console
